### ISSUE TITLE
After upgrading to 0.1.1, seeing unhandled PhantomJS error when running task

### ISSUE THREAD

**Issue by 1Copenut** [danbroooks/gulp-phantomcss#13]
I upgraded to Node 5.1.1 from 0.12 and upgraded all NPM modules. I jumped gulp-phantomCSS up to 0.1.1, but the next time I tried to run the task, it threw this error:

```
/* Gulp Task */
Starting 'jsTest:regression'...
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: spawn /Users/<username>/Documents/Development/C3/node_modules/gulp-phantomcss/node_modules/.bin/phantomjs ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:452:9)
    at process._tickCallback (node.js:366:17)
```

The error reads like it's coming from PhantomJS; I'll repost on the phantomCSS issue tracker if that'd be more appropriate.

Thank you.

**Comment by 1Copenut** [comment]
This might be a non-issue. I'm running El Capitan on OSX, and it won't allow for any PhantomJS lower than 2.0.0, which doesn't work with CasperJS. I'll look for a CasperJS port as the way forward.p

**Comment by gurtfrobe** [comment]
Bump - I'm getting the same error.

```
[15:09:06] Using gulpfile ~/Sites/drupal7/docroot/sites/all/themes/themename/gulpfile.js
[15:09:06] Starting 'phantomcss'...
[15:09:06] Finished 'phantomcss' after 9.33 ms
events.js:142
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/user/Sites/drupal7/docroot/sites/all/themes/themename/node_modules/gulp-phantomcss/node_modules/.bin/phantomjs ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:179:32)
    at onErrorNT (internal/child_process.js:345:16)
    at nextTickCallbackWith2Args (node.js:455:9)
    at process._tickCallback (node.js:369:17)

```

**Comment by jeremy-green** [comment]
Running `npm install` in `./node_modules/gulp-phantomcss` resolved the issue for me.

**Comment by 1Copenut** [comment]
@jeremy-green This solved it. Thank you for the simple, effective fix.

**Comment by digitor** [comment]
If you're on Windows this is because the path to the phantomjs binary needs a ".cmd" at the end. 
I've made a pull request with the fix here https://github.com/danbroooks/gulp-phantomcss/pull/14
Seemed to do the job for me on Windows 10.

**Comment by danbroooks** [comment]
Closing this following the recent updates, if there are still problems on windows please file a new issue
